export const Data = [
    {
        _id: 1,
        page_category: "Huile",
        title: "Huile Calmante",
        img: "https://assets.codepen.io/1159990/tokyo-tower.jpg",
        description: "loreum loreum loreum loreum loreum",
        composition: "Base MCT et CBD seul",
        contenance_number: "only",
        contenance: "15ml",
        choice: "multiple",
        taux: ["5%", "10%", "15%"],
        prix: [38.90, 59.90, 89.90],
        gout: "neutre",
        Provenance: "France",
        utilisation: "loreum loreum loreum loreum loreum",
        count: 1,
        isInCart: false
    },
    {
        _id: 2,
        page_category: "Huile",
        title: "Huile Relaxante",
        img: "https://assets.codepen.io/1159990/tokyo-tower.jpg",
        description: "loreum loreum loreum loreum loreum",
        composition: "Base MCT et CBD + CBG",
        contenance_number: "only",
        contenance: "10ml",
        choice: "multiple",
        taux: ["5%", "10%", "15%"],
        prix: [39.90, 49.90, 69.90],
        gout: "neutre",
        Provenance: "Europe",
        utilisation: "loreum loreum loreum loreum loreum",
        count: 1,
        isInCart: false
    },
    {
        _id: 3,
        page_category: "Huile",
        title: "Huile Anti-Stress",
        img: "https://assets.codepen.io/1159990/tokyo-tower.jpg",
        description: "loreum loreum loreum loreum loreum",
        composition: "Base MCT et CBD seul",
        contenance_number: "only",
        contenance: "10ml",
        choice: "only",
        taux: "10%",
        prix: 49.90,
        gout: "neutre",
        Provenance: "France",
        utilisation: "loreum loreum loreum loreum loreum",
        count: 1,
        isInCart: false
    },
    {
        _id: 4,
        page_category: "Huile",
        title: "Huile Anti-douleur",
        img: "https://assets.codepen.io/1159990/tokyo-tower.jpg",
        description: "loreum loreum loreum loreum loreum",
        composition: "Base MCT et CBD + CBG",
        contenance_number: "multiple",
        contenance: ["10ml", "20ml"],
        choice: "multiple",
        taux: ["10%", "10%", "10%"],
        prix: [59.90, 59.90, 59.90],
        gout: ["Citron vert", "Fraise", "Neutre"],
        Provenance: "France",
        utilisation: "loreum loreum loreum loreum loreum",
        count: 1,
        isInCart: false
    },
    {
        _id: 5,
        page_category: "Thé",
        title: "Infusion CBD Vitalité",
        img: "https://assets.codepen.io/1159990/tokyo-tower.jpg",
        description: "loreum loreum loreum loreum loreum",
        composition: "Neutre",
        choice: "only",
        taux: "10% de fleurs",
        prix: 14.90,
        gout: "Neutre",
        Provenance: "France",
        utilisation: "loreum loreum loreum loreum loreum",
        count: 1,
        isInCart: false
    },
    {
        _id: 6,
        page_category: "Thé",
        title: "Infusion CBD Digestion",
        img: "https://assets.codepen.io/1159990/tokyo-tower.jpg",
        description: "loreum loreum loreum loreum loreum",
        composition: "Mélisse, Verveine",
        taux: "10% de fleurs",
        prix: 14.90,
        gout: "Mélisse, Verveine",
        Provenance: "France",
        utilisation: "loreum loreum loreum loreum loreum",
        count: 1,
        isInCart: false
    },
    {
        _id: 7,
        page_category: "Thé",
        title: "Thé Anti-Stress",
        img: "https://assets.codepen.io/1159990/tokyo-tower.jpg",
        description: "loreum loreum loreum loreum loreum",
        composition: "Thé vert, Menthe, Citron",
        taux: "5% de fleurs",
        prix: 13.90,
        gout: "Menthe, Citron",
        Provenance: "France",
        utilisation: "loreum loreum loreum loreum loreum",
        count: 1,
        isInCart: false
    },
    {
        _id: 8,
        page_category: "Autre",
        title: "Gummies CBD",
        img: "https://assets.codepen.io/1159990/tokyo-tower.jpg",
        description: "loreum loreum loreum loreum loreum",
        composition: "Vegan, Mixed fruits",
        contenance: "60 Gummies",
        choice: "only",
        taux: "<2%",
        prix: 34.90,
        gout: "Mixed fruits",
        Provenance: "France",
        utilisation: "loreum loreum loreum loreum loreum",
        count: 1,
        isInCart: false
    },
    {
        _id: 9,
        page_category: "Autre",
        title: "Gummies CBD",
        img: "https://assets.codepen.io/1159990/tokyo-tower.jpg",
        description: "loreum loreum loreum loreum loreum",
        composition: "Vegan, Strawberry",
        contenance: "60 Gummies",
        choice: "only",
        taux: "<2%",
        prix: 34.90,
        gout: "Strawberry",
        Provenance: "France",
        utilisation: "loreum loreum loreum loreum loreum",
        count: 1,
        isInCart: false
    },
    {
        _id: 10,
        page_category: "Autre",
        title: "Gummies CBD",
        img: "https://assets.codepen.io/1159990/tokyo-tower.jpg",
        description: "loreum loreum loreum loreum loreum",
        composition: "Vegan",
        contenance: "60 Gummies",
        choice: "only",
        taux: "2.50%",
        prix: 29.90,
        gout: "Neutre",
        Provenance: "France",
        utilisation: "loreum loreum loreum loreum loreum",
        count: 1,
        isInCart: false
    }
    ]
   

    ////////////////////////////////////////////////////

// [
//     {
//         "id": "1",
//         "page_category": "Huile",
//         "product_category": "Huile Calmante",
//         "description": "loreum loreum loreum loreum loreum",
//         "composition": "Base MCT et CBD seul",
//         "contenance": "15ml",
//         "choice": "multiple",
//         "taux": ["5%", "10%", "15%"],
//         "prix": ["38.90", "59.90", "89.90"],
//         "gout": "neutre",
//         "utilisation": "loreum loreum loreum loreum loreum"
//     },
//     {
//         "id": "2",
//         "page_category": "Huile",
//         "product_category": "Huile Relaxante",
//         "description": "loreum loreum loreum loreum loreum",
//         "composition": "Base MCT et CBD + CBG",
//         "contenance": "10ml",
//         "choice": "multiple",
//         "taux": ["5%", "10%", "15%"],
//         "prix": ["39.90", "49.90", "69.90"],
//         "gout": "neutre",
//         "Provenance": "France",
//         "utilisation": "loreum loreum loreum loreum loreum"
//     },
//     {
//         "id": "3",
//         "page_category": "Huile",
//         "product_category": "Huile Anti-Stress",
//         "description": "loreum loreum loreum loreum loreum",
//         "composition": "Base MCT et CBD seul",
//         "contenance": "10ml",
//         "choice": "only",
//         "taux": "10%",
//         "prix": "49.90",
//         "gout": "neutre",
//         "Provenance": "France",
//         "utilisation": "loreum loreum loreum loreum loreum"
//     },
//     {
//         "id": "4",
//         "page_category": "Huile",
//         "product_category": "Huile Anti-douleur",
//         "description": "loreum loreum loreum loreum loreum",
//         "composition": "Base MCT et CBD + CBG",
//         "contenance": ["10ml", "20ml", "20ml"],
//         "choice": "multiple",
//         "taux": "10%",
//         "prix": "59.90",
//         "gout": ["Citron vert", "Fraise", "Neutre"],
//         "Provenance": "France",
//         "utilisation": "loreum loreum loreum loreum loreum"
//     },
//     {
//         "id": "5",
//         "page_category": "Thé",
//         "product_category": "Infusion CBD Vitalité",
//         "description": "loreum loreum loreum loreum loreum",
//         "composition": "Neutre",
//         "choice": "only",
//         "taux": "10% de fleurs",
//         "prix": "14.90",
//         "gout": "Neutre",
//         "Provenance": "France",
//         "utilisation": "loreum loreum loreum loreum loreum"
//     },
//     {
//         "id": "6",
//         "page_category": "Thé",
//         "product_category": "Infusion CBD Digestion",
//         "description": "loreum loreum loreum loreum loreum",
//         "composition": "Mélisse, Verveine",
//         "contenance": ["10ml", "20ml", "20ml"],
//         "choice": "multiple",
//         "taux": "10% de fleurs",
//         "prix": "14.90",
//         "gout": "Mélisse, Verveine",
//         "Provenance": "France",
//         "utilisation": "loreum loreum loreum loreum loreum"
//     },
//     {
//         "id": "7",
//         "page_category": "Huile",
//         "product_category": "Huile Anti-douleur",
//         "description": "loreum loreum loreum loreum loreum",
//         "composition": "Thé vert, Menthe, Citron",
//         "contenance": ["10ml", "20ml", "20ml"],
//         "choice": "multiple",
//         "taux": "5% de fleurs",
//         "prix": "13.90",
//         "gout": "Menthe, Citron",
//         "Provenance": "France",
//         "utilisation": "loreum loreum loreum loreum loreum"
//     },
//     {
//         "id": "8",
//         "page_category": "Autre",
//         "product_category": "Gummies CBD",
//         "description": "loreum loreum loreum loreum loreum",
//         "composition": "Vegan, Mixed fruits",
//         "contenance": "60 Gummies",
//         "choice": "only",
//         "taux": "<2%",
//         "prix": "34.90",
//         "gout": "Mixed fruits",
//         "Provenance": "France",
//         "utilisation": "loreum loreum loreum loreum loreum"
//     },
//     {
//         "id": "9",
//         "page_category": "Autre",
//         "product_category": "Gummies CBD",
//         "description": "loreum loreum loreum loreum loreum",
//         "composition": "Vegan, Strawberry",
//         "contenance": "60 Gummies",
//         "choice": "only",
//         "taux": "<2%",
//         "prix": "34.90",
//         "gout": "Strawberry",
//         "Provenance": "France",
//         "utilisation": "loreum loreum loreum loreum loreum"
//     },
//     {
//         "id": "10",
//         "page_category": "Autre",
//         "product_category": "Gummies CBD",
//         "description": "loreum loreum loreum loreum loreum",
//         "composition": "Vegan",
//         "contenance": "60 Gummies",
//         "choice": "only",
//         "taux": "2.50%",
//         "prix": "29.90",
//         "gout": "Neutre",
//         "Provenance": "France",
//         "utilisation": "loreum loreum loreum loreum loreum"
//     }
// ]