// export const Data = [
//     {
//         _id: 1,
//         page_category: "Huile",
//         title: "Huile Calmante",
//         img: "https://assets.codepen.io/1159990/tokyo-tower.jpg",
//         description: "loreum loreum loreum loreum loreum",
//         composition: "Base MCT et CBD seul",
//         contenance_number: "only",
//         contenance: "15ml",
//         choice: "multiple",
//         taux: ["5%", "10%", "15%"],
//         prix: [38.90, 59.90, 89.90],
//         gout: "neutre",
//         Provenance: "France",
//         utilisation: "loreum loreum loreum loreum loreum",
//         count: 1,
//         isInCart: false
//     },
//     {
//         _id: 2,
//         page_category: "Huile",
//         title: "Huile Relaxante",
//         img: "https://assets.codepen.io/1159990/tokyo-tower.jpg",
//         description: "loreum loreum loreum loreum loreum",
//         composition: "Base MCT et CBD + CBG",
//         contenance_number: "only",
//         contenance: "10ml",
//         choice: "multiple",
//         taux: ["5%", "10%", "15%"],
//         prix: [39.90, 49.90, 69.90],
//         gout: "neutre",
//         Provenance: "Europe",
//         utilisation: "loreum loreum loreum loreum loreum",
//         count: 1,
//         isInCart: false
//     },
//     {
//         _id: 3,
//         page_category: "Huile",
//         title: "Huile Anti-Stress",
//         img: "https://assets.codepen.io/1159990/tokyo-tower.jpg",
//         description: "loreum loreum loreum loreum loreum",
//         composition: "Base MCT et CBD seul",
//         contenance_number: "only",
//         contenance: "10ml",
//         choice: "only",
//         taux: "10%",
//         prix: 49.90,
//         gout: "neutre",
//         Provenance: "France",
//         utilisation: "loreum loreum loreum loreum loreum",
//         count: 1,
//         isInCart: false
//     },
//     {
//         _id: 4,
//         page_category: "Huile",
//         title: "Huile Anti-douleur",
//         img: "https://assets.codepen.io/1159990/tokyo-tower.jpg",
//         description: "loreum loreum loreum loreum loreum",
//         composition: "Base MCT et CBD + CBG",
//         contenance_number: "multiple",
//         contenance: ["10ml", "20ml"],
//         choice: "multiple",
//         taux: ["10%", "10%", "10%"],
//         prix: [59.90, 59.90, 59.90],
//         gout: ["Citron vert", "Fraise", "Neutre"],
//         Provenance: "France",
//         utilisation: "loreum loreum loreum loreum loreum",
//         count: 1,
//         isInCart: false
//     },
//     {
//         _id: 5,
//         page_category: "Thé",
//         title: "Infusion CBD Vitalité",
//         img: "https://assets.codepen.io/1159990/tokyo-tower.jpg",
//         description: "loreum loreum loreum loreum loreum",
//         composition: "Neutre",
//         choice: "only",
//         taux: "10% de fleurs",
//         prix: 14.90,
//         gout: "Neutre",
//         Provenance: "France",
//         utilisation: "loreum loreum loreum loreum loreum",
//         count: 1,
//         isInCart: false
//     },
//     {
//         _id: 6,
//         page_category: "Thé",
//         title: "Infusion CBD Digestion",
//         img: "https://assets.codepen.io/1159990/tokyo-tower.jpg",
//         description: "loreum loreum loreum loreum loreum",
//         composition: "Mélisse, Verveine",
//         taux: "10% de fleurs",
//         prix: 14.90,
//         gout: "Mélisse, Verveine",
//         Provenance: "France",
//         utilisation: "loreum loreum loreum loreum loreum",
//         count: 1,
//         isInCart: false
//     },
//     {
//         _id: 7,
//         page_category: "Thé",
//         title: "Thé Anti-Stress",
//         img: "https://assets.codepen.io/1159990/tokyo-tower.jpg",
//         description: "loreum loreum loreum loreum loreum",
//         composition: "Thé vert, Menthe, Citron",
//         taux: "5% de fleurs",
//         prix: 13.90,
//         gout: "Menthe, Citron",
//         Provenance: "France",
//         utilisation: "loreum loreum loreum loreum loreum",
//         count: 1,
//         isInCart: false
//     },
//     {
//         _id: 8,
//         page_category: "Autre",
//         title: "Gummies CBD",
//         img: "https://assets.codepen.io/1159990/tokyo-tower.jpg",
//         description: "loreum loreum loreum loreum loreum",
//         composition: "Vegan, Mixed fruits",
//         contenance: "60 Gummies",
//         choice: "only",
//         taux: "<2%",
//         prix: 34.90,
//         gout: "Mixed fruits",
//         Provenance: "France",
//         utilisation: "loreum loreum loreum loreum loreum",
//         count: 1,
//         isInCart: false
//     },
//     {
//         _id: 9,
//         page_category: "Autre",
//         title: "Gummies CBD",
//         img: "https://assets.codepen.io/1159990/tokyo-tower.jpg",
//         description: "loreum loreum loreum loreum loreum",
//         composition: "Vegan, Strawberry",
//         contenance: "60 Gummies",
//         choice: "only",
//         taux: "<2%",
//         prix: 34.90,
//         gout: "Strawberry",
//         Provenance: "France",
//         utilisation: "loreum loreum loreum loreum loreum",
//         count: 1,
//         isInCart: false
//     },
//     {
//         _id: 10,
//         page_category: "Autre",
//         title: "Gummies CBD",
//         img: "https://assets.codepen.io/1159990/tokyo-tower.jpg",
//         description: "loreum loreum loreum loreum loreum",
//         composition: "Vegan",
//         contenance: "60 Gummies",
//         choice: "only",
//         taux: "2.50%",
//         prix: 29.90,
//         gout: "Neutre",
//         Provenance: "France",
//         utilisation: "loreum loreum loreum loreum loreum",
//         count: 1,
//         isInCart: false
//     }
//     ]
   

    ////////////////////////////////////////////////////


    export const Data = [
         // HUILE CALMANTE //
  {
    _id: 1,
    url: "HuileCalmante",
    page_position: "first",
    page_category: "Huile",
    title: "Huile Calmante 1",
    img: "https://assets.codepen.io/1159990/tokyo-tower.jpg",
    taux: "5%",
    composition: "Base MCT et CBD seul",
    contenance: "5ml",
    gout: "Neutre",
    prix: 38.90,
    Provenance: "France",
    description: "description description description",
    utilisation: "utilisation utilisation utilisation",
    count: 1,
    // isInCart: false
},
{
    _id: 2,
    url: "HuileCalmante",
    page_category: "Huile",
    title: "Huile Calmante 2",
    img: "https://assets.codepen.io/1159990/tokyo-tower.jpg",
    taux: "10%",
    composition: "Base MCT et CBD seul",
    contenance: "15ml",
    gout: "Neutre",
    prix: 59.90,
    Provenance: "France",
    description: "description description description",
    utilisation: "utilisation utilisation utilisation",
    count: 1,
    // isInCart: false
},
{
    _id: 3,
    url: "HuileCalmante",
    page_category: "Huile",
    subCategory: "huileCalmante",
    title: "Huile Calmante 3",
    img: "https://assets.codepen.io/1159990/tokyo-tower.jpg",
    taux: "15%",
    composition: "Base MCT et CBD seul",
    contenance: "15ml",
    gout: "Neutre",
    prix: 89.90,
    Provenance: "France",
    description: "description description description",
    utilisation: "utilisation utilisation utilisation",
    count: 1,
    // isInCart: false
},
    // HUILE RELAXANTE //
{
    _id: 4, 
    url: "HuileRelaxante",
    page_position: "first",
    page_category: "Huile",
    title: "Huile Relaxante 1",
    img: "https://assets.codepen.io/1159990/tokyo-tower.jpg",
    taux: "5%",
    composition: "Base MCT et CBD + CBG",
    contenance: "10ml",
    gout: "Neutre",
    prix: 39.90,
    Provenance: "Europe",
    description: "description description description",
    utilisation: "utilisation utilisation utilisation",
    count: 1,
    // isInCart: false
},
{
    _id: 5, 
    url: "HuileRelaxante",
    page_category: "Huile",
    title: "Huile Relaxante 2",
    img: "https://assets.codepen.io/1159990/tokyo-tower.jpg",
    taux: "10%",
    composition: "Base MCT et CBD seul",
    contenance: "10ml",
    gout: "Neutre",
    prix: 49.90,
    Provenance: "Europe",
    description: "description description description",
    utilisation: "utilisation utilisation utilisation",
    count: 1,
    // isInCart: false
},
{
    _id: 6, 
    url: "HuileRelaxante",
    page_category: "Huile",
    title: "Huile Relaxante 3",
    img: "https://assets.codepen.io/1159990/tokyo-tower.jpg",
    taux: "15%",
    composition: "Base MCT et CBD seul",
    contenance: "10ml",
    gout: "Neutre",
    prix: 69.90,
    Provenance: "Europe",
    description: "description description description",
    utilisation: "utilisation utilisation utilisation",
    count: 1,
    // isInCart: false
},
// HUILE ANTI-STRESS //
{
    _id: 7, 
    url: "HuileAntiStress",
    page_position: "first",
    page_category: "Huile",
    title: "Huile Anti-Stress",
    img: "https://assets.codepen.io/1159990/tokyo-tower.jpg",
    taux: "10%",
    composition: "Base MCT et CBD seul",
    contenance: "10ml",
    gout: "Neutre",
    prix: 49.90,
    Provenance: "France",
    description: "description description description",
    utilisation: "utilisation utilisation utilisation",
    count: 1,
    // isInCart: false
},
// HUILE ANTI-DOULEUR //
{
    _id: 8, 
    url: "HuileAntiDouleur",
    page_position: "first",
    page_category: "Huile",
    title: "Huile Anti-douleur 1",
    img: "https://assets.codepen.io/1159990/tokyo-tower.jpg",
    taux: "10%",
    composition: "Base MCT, CBD + CBG",
    contenance: "10ml",
    gout: "Citron Vert",
    prix: 59.90,
    Provenance: "France",
    description: "description description description",
    utilisation: "utilisation utilisation utilisation",
    count: 1,
    // isInCart: false
},
{
    _id: 9, 
    url: "HuileAntiDouleur",
    page_category: "Huile",
    title: "Huile Anti-douleur 2",
    img: "https://assets.codepen.io/1159990/tokyo-tower.jpg",
    taux: "10%",
    composition: "Base MCT, CBD + CBG",
    contenance: "20ml",
    gout: "Fraise",
    prix: 59.90,
    Provenance: "France",
    description: "description description description",
    utilisation: "utilisation utilisation utilisation",
    count: 1,
    // isInCart: false
},
{
    _id: 10, 
    url: "HuileAntiDouleur",
    page_category: "Huile",
    title: "Huile Anti-douleur 3",
    img: "https://assets.codepen.io/1159990/tokyo-tower.jpg",
    taux: "10%",
    composition: "Base MCT, CBD + CBG",
    contenance: "20ml",
    gout: "Neutre",
    prix: 59.90,
    Provenance: "France",
    description: "description description description",
    utilisation: "utilisation utilisation utilisation",
    count: 1,
    // isInCart: false
},
////// Thé //////
{
    _id: 11, 
    url: "urlThé",
    page_position: "first",
    page_category: "The",
    title: "Infusion CBD Vitalité",
    img: "https://assets.codepen.io/1159990/tokyo-tower.jpg",
    taux: "10% de fleurs ",
    composition: "Neutre",
    gout: "Neutre",
    prix: 14.90,
    Provenance: "France",
    description: "description description description",
    utilisation: "utilisation utilisation utilisation",
    count: 1,
    // isInCart: false
},
{
    _id: 12, 
    url: "urlThé",
    page_position: "first",
    page_category: "The",
    title: "Infusion CBD Digestion ",
    img: "https://assets.codepen.io/1159990/tokyo-tower.jpg",
    taux: "10% de fleurs ",
    composition: "Mélisse, Verveine",
    gout: "Mélisse, Verveine",
    prix: 14.90,
    Provenance: "France",
    description: "description description description",
    utilisation: "utilisation utilisation utilisation",
    count: 1,
    // isInCart: false
},
{
    _id: 13, 
    url: "urlThé",
    page_position: "first",
    page_category: "The",
    title: "Thé Anti-Stress",
    img: "https://assets.codepen.io/1159990/tokyo-tower.jpg",
    taux: "5% de fleurs ",
    composition: "Thé vert, Menthe, Citron",
    gout: "Menthe, Citron",
    prix: 13.90,
    Provenance: "France",
    description: "description description description",
    utilisation: "utilisation utilisation utilisation",
    count: 1,
    // isInCart: false
},
// AUTRE (bonbon) //
{
    _id: 14, 
    subPage: "SubAutre",
    page_position: "first",
    page_category: "Autre",
    title: "Gummies CBD 1",
    img: "https://assets.codepen.io/1159990/tokyo-tower.jpg",
    taux: "<2%",
    composition: "Vegan Mixed Fruits",
    contenance: "60 gummies",
    gout: "Mixed Fruits",
    prix: 34.90,
    Provenance: "France",
    description: "description description description",
    utilisation: "utilisation utilisation utilisation",
    count: 1,
    // isInCart: false
},
{
    _id: 15, 
    page_category: "Autre",
    title: "Gummies CBD 2",
    img: "https://assets.codepen.io/1159990/tokyo-tower.jpg",
    taux: "<2%",
    composition: "Vegan Strawberry",
    contenance: "60 gummies",
    gout: "Strawberry",
    prix: 34.90,
    Provenance: "France",
    description: "description description description",
    utilisation: "utilisation utilisation utilisation",
    count: 1,
    // isInCart: false
},
{
    _id: 16, 
    subPage: "SubAutre",
    page_position: "first",
    page_category: "Autre",
    title: "Bonbons colorés",
    img: "https://assets.codepen.io/1159990/tokyo-tower.jpg",
    taux: "2.50%",
    composition: "Vegan",
    contenance: "30 gummies",
    gout: "Neutre",
    prix: 29.90,
    Provenance: "France",
    description: "description description description",
    utilisation: "utilisation utilisation utilisation",
    count: 1,
    // isInCart: false
},
    ]