
    export const Data = [
         // HUILE CALMANTE //
  {
    _id: 1,
    url: "HuileCalmante",
    page_position: "first",
    page_category: "Huile",
    title: "Huile Calmante 1",
    img: "https://assets.codepen.io/1159990/tokyo-tower.jpg",
    taux: "5%",
    composition: "Base MCT et CBD seul",
    contenance: "5ml",
    gout: "Neutre",
    prix: 38.90,
    Provenance: "France",
    description: "description description description",
    utilisation: "utilisation utilisation utilisation",
    count: 1,
    // isInCart: false
},
{
    _id: 2,
    url: "HuileCalmante",
    page_category: "Huile",
    title: "Huile Calmante 2",
    img: "https://assets.codepen.io/1159990/tokyo-tower.jpg",
    taux: "10%",
    composition: "Base MCT et CBD seul",
    contenance: "15ml",
    gout: "Neutre",
    prix: 59.90,
    Provenance: "France",
    description: "description description description",
    utilisation: "utilisation utilisation utilisation",
    count: 1,
    // isInCart: false
},
{
    _id: 3,
    url: "HuileCalmante",
    page_category: "Huile",
    subCategory: "huileCalmante",
    title: "Huile Calmante 3",
    img: "https://assets.codepen.io/1159990/tokyo-tower.jpg",
    taux: "15%",
    composition: "Base MCT et CBD seul",
    contenance: "15ml",
    gout: "Neutre",
    prix: 89.90,
    Provenance: "France",
    description: "description description description",
    utilisation: "utilisation utilisation utilisation",
    count: 1,
    // isInCart: false
},
    // HUILE RELAXANTE //
{
    _id: 4, 
    url: "HuileRelaxante",
    page_position: "first",
    page_category: "Huile",
    title: "Huile Relaxante 1",
    img: "https://assets.codepen.io/1159990/tokyo-tower.jpg",
    taux: "5%",
    composition: "Base MCT et CBD + CBG",
    contenance: "10ml",
    gout: "Neutre",
    prix: 39.90,
    Provenance: "Europe",
    description: "description description description",
    utilisation: "utilisation utilisation utilisation",
    count: 1,
    // isInCart: false
},
{
    _id: 5, 
    url: "HuileRelaxante",
    page_category: "Huile",
    title: "Huile Relaxante 2",
    img: "https://assets.codepen.io/1159990/tokyo-tower.jpg",
    taux: "10%",
    composition: "Base MCT et CBD seul",
    contenance: "10ml",
    gout: "Neutre",
    prix: 49.90,
    Provenance: "Europe",
    description: "description description description",
    utilisation: "utilisation utilisation utilisation",
    count: 1,
    // isInCart: false
},
{
    _id: 6, 
    url: "HuileRelaxante",
    page_category: "Huile",
    title: "Huile Relaxante 3",
    img: "https://assets.codepen.io/1159990/tokyo-tower.jpg",
    taux: "15%",
    composition: "Base MCT et CBD seul",
    contenance: "10ml",
    gout: "Neutre",
    prix: 69.90,
    Provenance: "Europe",
    description: "description description description",
    utilisation: "utilisation utilisation utilisation",
    count: 1,
    // isInCart: false
},
// HUILE ANTI-STRESS //
{
    _id: 7, 
    url: "HuileAntiStress",
    page_position: "first",
    page_category: "Huile",
    title: "Huile Anti-Stress",
    img: "https://assets.codepen.io/1159990/tokyo-tower.jpg",
    taux: "10%",
    composition: "Base MCT et CBD seul",
    contenance: "10ml",
    gout: "Neutre",
    prix: 49.90,
    Provenance: "France",
    description: "description description description",
    utilisation: "utilisation utilisation utilisation",
    count: 1,
    // isInCart: false
},
// HUILE ANTI-DOULEUR //
{
    _id: 8, 
    url: "HuileAntiDouleur",
    page_position: "first",
    page_category: "Huile",
    title: "Huile Anti-douleur 1",
    img: "https://assets.codepen.io/1159990/tokyo-tower.jpg",
    taux: "10%",
    composition: "Base MCT, CBD + CBG",
    contenance: "10ml",
    gout: "Citron Vert",
    prix: 59.90,
    Provenance: "France",
    description: "description description description",
    utilisation: "utilisation utilisation utilisation",
    count: 1,
    // isInCart: false
},
{
    _id: 9, 
    url: "HuileAntiDouleur",
    page_category: "Huile",
    title: "Huile Anti-douleur 2",
    img: "https://assets.codepen.io/1159990/tokyo-tower.jpg",
    taux: "10%",
    composition: "Base MCT, CBD + CBG",
    contenance: "20ml",
    gout: "Fraise",
    prix: 59.90,
    Provenance: "France",
    description: "description description description",
    utilisation: "utilisation utilisation utilisation",
    count: 1,
    // isInCart: false
},
{
    _id: 10, 
    url: "HuileAntiDouleur",
    page_category: "Huile",
    title: "Huile Anti-douleur 3",
    img: "https://assets.codepen.io/1159990/tokyo-tower.jpg",
    taux: "10%",
    composition: "Base MCT, CBD + CBG",
    contenance: "20ml",
    gout: "Neutre",
    prix: 59.90,
    Provenance: "France",
    description: "description description description",
    utilisation: "utilisation utilisation utilisation",
    count: 1,
    // isInCart: false
},
////// Thé //////
{
    _id: 11, 
    url: "urlThé",
    page_position: "first",
    page_category: "The",
    title: "Infusion CBD Vitalité",
    img: "https://assets.codepen.io/1159990/tokyo-tower.jpg",
    taux: "10% de fleurs ",
    composition: "Neutre",
    gout: "Neutre",
    prix: 14.90,
    Provenance: "France",
    description: "description description description",
    utilisation: "utilisation utilisation utilisation",
    count: 1,
    // isInCart: false
},
{
    _id: 12, 
    url: "urlThé",
    page_position: "first",
    page_category: "The",
    title: "Infusion CBD Digestion ",
    img: "https://assets.codepen.io/1159990/tokyo-tower.jpg",
    taux: "10% de fleurs ",
    composition: "Mélisse, Verveine",
    gout: "Mélisse, Verveine",
    prix: 14.90,
    Provenance: "France",
    description: "description description description",
    utilisation: "utilisation utilisation utilisation",
    count: 1,
    // isInCart: false
},
{
    _id: 13, 
    url: "urlThé",
    page_position: "first",
    page_category: "The",
    title: "Thé Anti-Stress",
    img: "https://assets.codepen.io/1159990/tokyo-tower.jpg",
    taux: "5% de fleurs ",
    composition: "Thé vert, Menthe, Citron",
    gout: "Menthe, Citron",
    prix: 13.90,
    Provenance: "France",
    description: "description description description",
    utilisation: "utilisation utilisation utilisation",
    count: 1,
    // isInCart: false
},
// AUTRE (bonbon) //
{
    _id: 14, 
    subPage: "SubAutre",
    page_position: "first",
    page_category: "Autre",
    title: "Gummies CBD 1",
    img: "https://assets.codepen.io/1159990/tokyo-tower.jpg",
    taux: "<2%",
    composition: "Vegan Mixed Fruits",
    contenance: "60 gummies",
    gout: "Mixed Fruits",
    prix: 34.90,
    Provenance: "France",
    description: "description description description",
    utilisation: "utilisation utilisation utilisation",
    count: 1,
    // isInCart: false
},
{
    _id: 15, 
    page_category: "Autre",
    title: "Gummies CBD 2",
    img: "https://assets.codepen.io/1159990/tokyo-tower.jpg",
    taux: "<2%",
    composition: "Vegan Strawberry",
    contenance: "60 gummies",
    gout: "Strawberry",
    prix: 34.90,
    Provenance: "France",
    description: "description description description",
    utilisation: "utilisation utilisation utilisation",
    count: 1,
    // isInCart: false
},
{
    _id: 16, 
    subPage: "SubAutre",
    page_position: "first",
    page_category: "Autre",
    title: "Bonbons colorés",
    img: "https://assets.codepen.io/1159990/tokyo-tower.jpg",
    taux: "2.50%",
    composition: "Vegan",
    contenance: "30 gummies",
    gout: "Neutre",
    prix: 29.90,
    Provenance: "France",
    description: "description description description",
    utilisation: "utilisation utilisation utilisation",
    count: 1,
    // isInCart: false
},
    ]